"""
Core.scene -- scene/collection/object helpers.

The main entry point for placing procedural assets is :func:`gn_object`, which
creates an (empty) mesh object carrying a Geometry Nodes modifier that points
at an asset node group.  Group inputs are set *by name*, so scene code reads
like data::

    gn_object("Desk.012", get_asset("MIL.Desk"), {"Width": 0.62},
              location=(1, 2, 0), collection=furniture)
"""
from __future__ import annotations

import math

import bpy
from mathutils import Euler, Matrix, Vector

__all__ = ["reset_scene", "collection", "gn_object", "set_gn_inputs", "empty",
           "link", "hide"]


def reset_scene(keep_worlds=False):
    """Start from an empty scene with default settings.

    Safe inside a running Blender UI (a script run from the Text Editor):
    reloading factory settings would tear down the very UI that runs the
    script, so instead a fresh scene replaces all existing scenes and every
    data-block kind a build creates is removed.  Texts, screens and
    workspaces are left alone."""
    old = list(bpy.data.scenes)
    sc = bpy.data.scenes.new("Scene")
    wm = bpy.context.window_manager
    for win in (wm.windows if wm else ()):
        win.scene = sc
    # Freestyle line sets hold a collection pointer that ID removal does not
    # release cleanly (user-count error): drop them explicitly first
    for s in old:
        for vl in s.view_layers:
            fs = vl.freestyle_settings
            for ls in list(fs.linesets):
                ls.select_by_collection = False
                ls.collection = None
                fs.linesets.remove(ls)
    # then the data, then the old scenes
    kinds = ["objects", "meshes", "curves", "cameras", "lights", "materials", "node_groups",
             "collections", "images", "textures", "linestyles", "actions"]
    if not keep_worlds:
        kinds.append("worlds")
    doomed = [idb for k in kinds for idb in getattr(bpy.data, k, ())
              if not (k == "images" and idb.type in {"RENDER_RESULT", "COMPOSITING"})]
    if doomed:
        bpy.data.batch_remove(doomed)
    for s in old:
        bpy.data.scenes.remove(s)
    sc.unit_settings.system = "METRIC"
    sc.unit_settings.scale_length = 1.0
    return sc


def collection(name, parent=None, color=None):
    """Get or create a collection linked under ``parent`` (default: scene root)."""
    col = bpy.data.collections.get(name)
    if col is None:
        col = bpy.data.collections.new(name)
    parent = parent or bpy.context.scene.collection
    if col.name not in [c.name for c in parent.children]:
        parent.children.link(col)
    if color:
        try:
            col.color_tag = color
        except TypeError:
            pass
    return col


def link(obj, col=None):
    col = col or bpy.context.scene.collection
    for c in list(obj.users_collection):
        c.objects.unlink(obj)
    col.objects.link(obj)
    return obj


def _interface_inputs(ng):
    return [it for it in ng.interface.items_tree
            if getattr(it, "item_type", "SOCKET") == "SOCKET" and it.in_out == "INPUT"]


def _set_mod_input(mod, ident, v):
    # Blender 5.2+: typed accessors under ``mod.properties.inputs``
    props = getattr(mod, "properties", None)
    if props is not None and hasattr(props, "inputs"):
        slot = getattr(props.inputs, ident, None)
        if slot is not None:
            slot.value = v
            return
    # Blender 4.x - 5.1: ID properties on the modifier
    mod[ident] = v


def get_gn_input(mod, name):
    items = {it.name: it for it in _interface_inputs(mod.node_group)}
    ident = items[name].identifier
    props = getattr(mod, "properties", None)
    if props is not None and hasattr(props, "inputs"):
        slot = getattr(props.inputs, ident, None)
        if slot is not None:
            return slot.value
    return mod[ident]


def set_gn_inputs(mod, values: dict):
    """Set GN modifier inputs by *interface name*."""
    ng = mod.node_group
    items = {it.name: it for it in _interface_inputs(ng)}
    for k, v in (values or {}).items():
        it = items.get(k)
        if it is None:
            raise KeyError(f"{ng.name}: no input '{k}'. Inputs: {list(items)}")
        if isinstance(v, (tuple, list)):
            v = tuple(float(x) for x in v)
            if it.socket_type == "NodeSocketColor" and len(v) == 3:
                v = (*v, 1.0)
        if it.socket_type == "NodeSocketInt" and isinstance(v, float):
            v = int(round(v))
        if it.socket_type == "NodeSocketBool":
            v = bool(v)
        _set_mod_input(mod, it.identifier, v)
    return mod


def gn_object(name, node_group, inputs=None, location=(0, 0, 0), rotation=(0, 0, 0),
              scale=(1, 1, 1), collection=None, parent=None):
    """Create an object whose geometry is fully generated by ``node_group``."""
    me = bpy.data.meshes.new(name)
    ob = bpy.data.objects.new(name, me)
    (collection or bpy.context.scene.collection).objects.link(ob)
    mod = ob.modifiers.new("GeometryNodes", "NODES")
    mod.node_group = node_group
    set_gn_inputs(mod, inputs)
    ob.location = location
    ob.rotation_euler = rotation
    ob.scale = scale
    if parent is not None:
        ob.parent = parent
    return ob


def empty(name, location=(0, 0, 0), rotation=(0, 0, 0), collection=None, display="PLAIN_AXES",
          size=0.5, parent=None):
    ob = bpy.data.objects.new(name, None)
    ob.empty_display_type = display
    ob.empty_display_size = size
    ob.location = location
    ob.rotation_euler = rotation
    (collection or bpy.context.scene.collection).objects.link(ob)
    if parent is not None:
        ob.parent = parent
    return ob


def hide(obj_or_col, render=True, viewport=True):
    obj_or_col.hide_render = render
    if hasattr(obj_or_col, "hide_viewport"):
        obj_or_col.hide_viewport = viewport


def matrix_from(location=(0, 0, 0), rot_deg=(0, 0, 0)):
    r = Euler([math.radians(a) for a in rot_deg]).to_matrix().to_4x4()
    return Matrix.Translation(Vector(location)) @ r
